### PR TITLE
Upgrade to Java 11

### PR DESCRIPTION
**Pull request by leszko**
Update to Java 11 and Alpine 3.11.

Comparison of image sizes

|                    | Java 8 (current) | Java 11 (this PR) |
|--------------|------------------|-------------------|
| hazelcast    |   78.97 MB         | 91.33 MB                        |
| hazelcast-enterprise |  85.28 MB  | 97.85 MB |

**Pros** of moving to Java 11:
- Keeping image up to date
- Using new features from Java 11 (like better GC, faster TLS)

**Cons** of moving to Java 11:
- (slightly) bigger docker images
- Non-backwards-compatibility in terms of Java internals
- (Alpine Linux version related) Netty-tcnative is compiled against the old (1.0.0) version of `libssl` which is not included in Alpine 3.9 and newer. We would need to use a version from Alpine 3.8.

------------------------------------------------------

[**archived below**] Issues already solved thanks to @kwart

I try to upgrade Alpine version and Java version, but I have a problem with OpenSSL. It fails with the exception below. The issue is with Alpine upgrade. It's fails even if I just upgraded Alpine to `11` and kept Java 8.

@kwart you're an expert here, could you help?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:474)
        at com.hazelcast.nio.ssl.OpenSSLEngineFactory.init(OpenSSLEngineFactory.java:76)
        at com.hazelcast.nio.ssl.AbstractTLSChannelInitializer.loadSSLEngineFactory(AbstractTLSChannelInitializer.java:47)
        at com.hazelcast.nio.ssl.AbstractTLSChannelInitializer.<init>(AbstractTLSChannelInitializer.java:25)
        at com.hazelcast.nio.ssl.UnifiedTLSChannelInitializer.<init>(UnifiedTLSChannelInitializer.java:51)
        at com.hazelcast.nio.EnterpriseChannelInitializerProvider.createUnifiedTlsChannelInitializer(EnterpriseChannelInitializerProvider.java:94)
        at com.hazelcast.nio.EnterpriseChannelInitializerProvider.<init>(EnterpriseChannelInitializerProvider.java:37)
        at com.hazelcast.instance.EnterpriseNodeExtension.createChannelInitializerProvider(EnterpriseNodeExtension.java:615)
        at com.hazelcast.instance.DefaultNodeContext.createNetworkingService(DefaultNodeContext.java:155)
        at com.hazelcast.instance.Node.<init>(Node.java:248)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:161)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:581)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:133)
        ... 16 more
        Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
                ... 18 more
        Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64.so
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
                ... 19 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: [/usr/lib/jvm/java-11-openjdk/lib/server, /usr/lib/jvm/java-11-openjdk/lib, /usr/lib/jvm/java-11-openjdk/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
                        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
                        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
                        at java.base/java.lang.System.loadLibrary(System.java:1870)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
                        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
                        ... 19 more
                        Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: [/usr/lib/jvm/java-11-openjdk/lib/server, /usr/lib/jvm/java-11-openjdk/lib, /usr/lib/jvm/java-11-openjdk/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
                                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
                                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
                                at java.base/java.lang.System.loadLibrary(System.java:1870)
                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
                                at java.base/java.security.AccessController.doPrivileged(Native Method)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
                                ... 20 more
```

### CODE REVIEW

**Comment by kwart** [comment]
The problem is in OpenSSL version. Alpine 3.9 updated the OpenSSL version from 1.0 to 1.1. Even the newest `netty-tcnative` is still compiled against OpenSSL 1.0 so it fails to load the (dynamically linked) dependencies.

There is a hacky way to workaround this. We could install the OpenSSL version from Alpine 3.8. The question is if we want to go this way.

**Comment by kwart** [comment]
The Workaround is added as a new commit.

**Comment by leszko** [comment]
> The problem is in OpenSSL version. Alpine 3.9 updated the OpenSSL version from 1.0 to 1.1. Even the newest `netty-tcnative` is still compiled against OpenSSL 1.0 so it fails to load the (dynamically linked) dependencies.
> 
> There is a hacky way to workaround this. We could install the OpenSSL version from Alpine 3.8. The question is if we want to go this way.

Thanks a lot @kwart :)

**Comment by pivovarit** [comment]
It's all a trade-off, I believe we could benefit more from an updated runtime than from saving X megabytes on the image size. 

However, it'd be great to obtain the exact numbers that we're talking about.

My concern is more about potential incompatibilities (user-provided jars can not work on JDK11, etc), but worst-case scenarios we could maintain two official images (JDK8 and JDK11-based one).

**Comment by Holmistr** [comment]
@pivovarit And of course, it should be configurable, but parallel GC as default creates the best out of the box experience for most users.

**Comment by pivovarit** [comment]
Totally, there's already mechanism put in place for managing default opts: https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-oss/Dockerfile#L17

**Comment by leszko** [comment]
1. Updated the description, added the image sizes and pros/cons for upgrading
2. Added Parallel GC by default

I think we should not maintain two images, or at least be more re-active than pro-active here. Meaning that if there are some issues reported, then start maybe maintaining both. To me it's like you should just use Hazelcast and not care about the underlying base image. And the cases that we break backwards-compatibility are very corner case and very deep (like someone depends on the Java internals in their user code deployment).

**Comment by kwart** [comment]
@leszko Was it intended to remove the `add-opens` arguments?
We have them described in the documentation - they should be used for Java 9 and newer - https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#running-in-modular-java

**Comment by leszko** [comment]
> @leszko Was it intended to remove the `add-opens` arguments?
> We have them described in the documentation - they should be used for Java 9 and newer - https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#running-in-modular-java

Ahh, sorry, I've seen them added in `hazelcast-enterprise`, but not in `hazelcast-oss` and though I added them by mistake. But, actually it's you who added them on purpose ;)

Added back.

**Comment by leszko** [comment]
Btw. I spoke with @jerrinot and we'll release this change together with `4.0` and keep Java 8 for the `3.12.x` maintenance.

**Pull request merged**
