### PR TITLE
Simplify EE Distribution URL computation [DI-167]

### PR DESCRIPTION
**Pull request by JackPGreen**
Rather than parsing the repositories' XML metadata, we can get the repository to do this for us.

The latest `5.4.1-SNAPSHOT` is (currently):
`https://repository.hazelcast.com/snapshot/com/hazelcast/hazelcast-enterprise-distribution/5.4.1-SNAPSHOT/hazelcast-enterprise-distribution-5.4.1-20240628.174049-12.zip`

`https://repository.hazelcast.com/snapshot/com/hazelcast/hazelcast-enterprise-distribution/5.4.1-SNAPSHOT/hazelcast-enterprise-distribution-5.4.1-SNAPSHOT.zip` resolves to download `hazelcast-enterprise-distribution-5.4.1-20240628.174049-12.zip` - i.e. the same file.

This also fixes the build, as the `5.4.0-SNAPSHOT` references in the unit test no longer exists - we only keep the latest versions distribution (e.g. now `5.4.1-SNAPSHOT`) `SNAPSHOT`.

Finally, we can remove `xmllint` as can replace it's now more-limited applications with built-in tooling.

Fixes: [DI-167](https://hazelcast.atlassian.net/browse/DI-167)

[DI-167]: https://hazelcast.atlassian.net/browse/DI-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ldziedziul — CHANGES_REQUESTED** [review]
We need to implement https://hazelcast.atlassian.net/browse/DI-163 first, before any changes to url resolution, we hit too many issues with it last days

**Review by ldziedziul — COMMENTED** [review]
Do we need xmllint?

**Comment by JackPGreen** [comment]
> Do we need xmllint?

Only for OS, not EE. But I’ve not refactored to remove from EE for consistency.

**Comment by ldziedziul** [comment]
> > Do we need xmllint?
> 
> Only for OS, not EE. But I’ve not refactored to remove from EE for consistency.

It seems that builtin `grep` does the same:
```diff
- curl --fail --silent --show-error --location "${repository_url}/${group_id//./\/}/${artifact_id}/maven-metadata.xml" | xmllint --xpath "string(/metadata/versioning/release)" -
+ curl --fail --silent --show-error --location "${repository_url}/${group_id//./\/}/${artifact_id}/maven-metadata.xml" | grep -oPm1 "(?<=<release>)[^<]+"
```

**Comment by JackPGreen** [comment]
> It seems that builtin `grep` does the same:
> 
> ```diff
> - curl --fail --silent --show-error --location "${repository_url}/${group_id//./\/}/${artifact_id}/maven-metadata.xml" | xmllint --xpath "string(/metadata/versioning/release)" -
> + curl --fail --silent --show-error --location "${repository_url}/${group_id//./\/}/${artifact_id}/maven-metadata.xml" | grep -oPm1 "(?<=<release>)[^<]+"
> ```

[It looks like not all built-in `grep` flavours have `-P`](https://stackoverflow.com/a/77662095), _but_ you can do the same with `awk` which seem to work on Mac instead.

Luckily, we have unit tests that cover this.

I've removed `xmllint` - 33fabc3fb0c726f4b5a211b12cd31f263135b889

**Comment by nishaatr** [comment]
> I've removed `xmllint` - [33fabc3](https://github.com/hazelcast/hazelcast-docker/commit/33fabc3fb0c726f4b5a211b12cd31f263135b889) - nice spot!

Personally preferred xmllint. More readable and exacting than regex IMO

**Comment by ldziedziul** [comment]
> Personally preferred xmllint. More readable and exacting than regex IMO

That's true, not perfect, but it requires an additional action and an extra step in every workflow where we use it

If we hit issues with version resolution we can revisit that

**Review by ldziedziul — APPROVED** [review]

**Review by nishaatr — APPROVED** [review]

**Pull request merged**
