### PR TITLE
Remove `server.sh` and `stop.sh` scripts & rework Dockerfiles for OSS and Enterprise

### PR DESCRIPTION
**Pull request by ps-jay**
This pull request:
- removes the `server.sh` and `stop.sh` scripts
- reworks the `Dockerfile` for both the OSS and Enterprise images
- updates the `README.md` to match the changes

As discussed in #16 and #62, the `server.sh` and `stop.sh` scripts aren't really required.

Hazelcast itself can run in the foreground of the container, and catch & handle `SIGTERM` signals on its' own.

This is particularly true, when you consider the use of the shutdown hook functionality - as discussed in #42.

These changes are _mostly_ backward compatible, if you're already using these images.

The container still behaves as if it has the `server.sh` script, for example it still makes use of the environment variables `HZ_LICENSE_KEY`, `MIN_HEAP_SIZE`, etc.

The backward incompatible change is that `docker exec` to call `stop.sh` no longer works.  Hence why I've updated the `README.md` to also mention the shutdown hooks - as this might be important for some installations.

Summary of changes to the `Dockerfile` for OSS and Enterprise:
- Update Alpine, and install `bash` in a single `RUN` command to reduce final image size 
- Removing the apk cache after installing `bash` & `curl` to reduce the final image size
- Add `curl`, so that we can use `curl` to download Hazelcast, unzip it, and delete the zip file in a single `RUN` command, again reducing the final image size
- Do not extract the `code-samples`, `demo`, or `docs` into the image, these would generally not be needed for Hazelcast server runtime - also reducing final image size
- Use `curl` also for cache api jar download for consistency
- Move the logic from `server.sh` into the `CMD` command - it's not the most neat looking `CMD`, but it preserves backward compatibilty with images built with `server.sh` in them

When compared to the current publically available `hazelcast/hazelcast-enterprise:3.10` image (sha256:c7515234fcbe80b664bf7704973cee0c9d1b44bfc9623db44ebff3b2fe148a75) this new image final image size is 114MB, down from 421MB.

### CODE REVIEW

**Comment by w0203j** [comment]
This is such a good improvements!

**Comment by hasancelik** [comment]
@ps-jay LGTM 👍 Could you please sign our Contributor Agreement to have the PR merged into Hazelcast repository?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by ps-jay** [comment]
Signed the CLA, and emailed it through.

**Comment by leszko** [comment]
Thanks @ps-jay

**Pull request merged**
