### PR TITLE
Default to JDK's default Garbage Collector with -XX:MaxGCPauseMillis=5

### PR DESCRIPTION
**Pull request by pivovarit**
closes: https://github.com/hazelcast/hazelcast-docker/issues/197
closes: https://github.com/hazelcast/hazelcast-docker/issues/196

### CODE REVIEW

**Review by hasancelik — APPROVED** [review]
👍

**Comment by jerrinot** [comment]
any idea about impact on throughput? 5ms is VERY aggressive.

**Comment by pivovarit** [comment]
I know. I'm relying here on @mtopolnik (https://github.com/hazelcast/hazelcast-docker/issues/197#issuecomment-734232379)

**Comment by mtopolnik** [comment]
5 ms works well with JDK 15. On JDK 11, 10 ms is maybe a safer option, but in my testing I only noticed G1 would simply end up making pauses longer than configured.

My testing was done on Jet streaming workloads; it is definitely a good idea to test specifically for other workloads we're interested in.

As a cross-check, Kafka configures max pause to 20 ms.

**Comment by cangencer** [comment]
Some benchmarks from @pveentjer : https://hazelcast.atlassian.net/wiki/spaces/PERF/pages/2875981979/HD+vs+G1+vs+ZGC#m5.xlarge

**Review by jerrinot — APPROVED** [review]

**Comment by pivovarit** [comment]
Merging this one. The next step will involve updating the JDK to the newest one

**Pull request merged**
