### PR TITLE
Enable ignore-unfixed option for Trivy

### PR DESCRIPTION
**Pull request by hasancelik**
Additional changes:
- use official trivy Github Action

Trivy steps at EE workflows are currently failing after I changed severity level to medium(its default valut is high):
https://github.com/hazelcast/hazelcast-docker/runs/3241439215?check_suite_focus=true
Snyk steps are not failing because Snyk ignores unfixed(won't fix) ones as a default behaviour:
https://support.snyk.io/hc/en-us/articles/360000923498-How-can-I-ignore-a-vulnerability- 

@leszko I checked most of medium vulns are reported by Trivy were marked as `will not fix` by RedHat so checking them one by one every time then adding into whitelist.yaml to make our builds are green again is just time-consumer. If vulnerability can not be fixed, it can be invisible for us. WDYT?

### CODE REVIEW

**Comment by leszko** [comment]
Hi @jerrinot wdyt?

As far as I understand there are just too many things we'd need to check manually and add to the whitelist, which is time-consuming. Do you have any idea for it?

**Comment by hasancelik** [comment]
Hi @jerrinot, what is your opinion?

**Comment by hasancelik** [comment]
It seems Snyk changed their policy about unfixed vulns:
```
 In addition, for Red Hat Enterprise Linux we will now show both fixed and unfixed CVEs, whereas the RHSA only shows fixed CVEs. For Amazon Linux, we will still only support fixed CVEs at this time. 
```
https://updates.snyk.io/ --> `Snyk Container Security Data Update to Red Hat Enterprise Linux (RHEL) and Amazon Linux`

**Comment by frant-hartm** [comment]
This has been done in https://github.com/hazelcast/hazelcast-docker/pull/373

**Pull request closed without merging**
