### PR TITLE
Make PR builder use `pull_request_target` to support Dependabot

### PR DESCRIPTION
**Pull request by JackPGreen**
Fixes https://github.com/hazelcast/hazelcast-docker/issues/763

### CODE REVIEW

**Comment by JackPGreen** [comment]
Needs further thought.

**Review by nishaatr — APPROVED** [review]

**Comment by ldziedziul** [comment]
That's not a solution. Simple switching to `pull_request_target` would make the workflow to test the code from `master` branch and not from the PR. So we wouldn't test PR changes before the merge. We would end up eventually with a broken `master`

I've asked Josef to enable AWS secrets for dependabot user, it should work now

**Review by ldziedziul — CHANGES_REQUESTED** [review]
I think we should close it

**Comment by JackPGreen** [comment]
> I've asked Josef to enable AWS secrets for dependabot user, it should work now

Perfect!

**Pull request closed without merging**
